config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'user_addresses', to: 'users/registrations#new_user_address'
    post 'user_addresses', to: 'users/registrations#create_user_address'
  end
  root to: "items#index"
  resources :items do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :purchase_records, only: [:index, :create]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
  resources :cards, only: [:new, :edit, :update, :create, :destroy]
  resources :categories, only: [:new]
  get '/category/:id', to: 'categories#search'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_item

  def create
    like = current_user.likes.build(item_id: params[:item_id])
    like.save
    respond_to(&:js)
  end

  def destroy
    like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    like.destroy
    respond_to(&:js)
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_favo.html.erb
<% if user_signed_in? && item.liked_by?(current_user) %>
  <%= link_to item_likes_path(item.id), data: { turbo_method: :delete }, class: "item_likes", remote: true do %>
    <%= image_tag "yellowstar.png", alt: "いいね済み", class:"favorite-star-icon" %>
  <% end %>
<% else %>
  <%= link_to item_likes_path(item.id), data: { turbo_method: :post }, class: "item_likes", remote: true do %>
    <%= image_tag "star.png", alt: "いいねする", class:"star-icon" %>
  <% end %>
<% end %>

app/views/likes/_like.html.erb
<% if user_signed_in? && item.liked_by?(current_user) %>
  <%= link_to item_likes_path(item.id), data: { turbo_method: :delete }, class: "item_likes", remote: true do %>
    <%= image_tag "yellowstar.png", alt: "いいね済み", class:"star-icon" %>
  <% end %>
<% else %>
  <%= link_to item_likes_path(item.id), data: { turbo_method: :post }, class: "item_likes", remote: true do %>
    <%= image_tag "star.png", alt: "いいねする", class:"star-icon" %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"