config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'user_addresses', to: 'users/registrations#new_user_address'
    post 'user_addresses', to: 'users/registrations#create_user_address'
  end
  root to: "items#index"
  resources :items do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :purchase_records, only: [:index, :create]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
  resources :cards, only: [:new, :edit, :update, :create, :destroy]
  resources :categories, only: [:new]
  get '/category/:id', to: 'categories#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  validates :nickname, presence: true
  validates :birth_date, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'

  validates :last_name, presence: true
  LAST_NAME_REGEX = /\A[ぁ-んァ-ヶ一-龥々ー]+\z/
  validates_format_of :last_name, with: LAST_NAME_REGEX, message: 'is invalid. Input full-width characters'

  validates :first_name, presence: true
  FIRST_NAME_REGEX = /\A[ぁ-んァ-ヶ一-龥々ー]+\z/
  validates_format_of :first_name, with: FIRST_NAME_REGEX, message: 'is invalid. Input full-width characters'

  validates :last_name_kana, presence: true
  LAST_NAME_KANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates_format_of :last_name_kana, with: LAST_NAME_KANA_REGEX, message: 'is invalid. Input full-width katakana characters'

  validates :first_name_kana, presence: true
  FIRST_NAME_KANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates_format_of :first_name_kana, with: FIRST_NAME_KANA_REGEX, message: 'is invalid. Input full-width katakana characters'

  has_many :items
  has_many :purchase_records
  has_one :card, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments
  has_one :user_address, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following, dependent: :destroy

  has_many :sns_credentials

  def followed_by?(user)
    return false unless user # userがnilの場合はfalseを返す

    follower = passive_relationships.find_by(following_id: user.id)
    follower.present?
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user:, sns: }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def new
    @user = User.new
  end

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
      super
    else
      @user = User.new(sign_up_params)
      render :new, status: :unprocessable_entity and return unless @user.valid?

      session['devise.regist_data'] = { user: @user.attributes }
      session['devise.regist_data'][:user]['password'] = params[:user][:password]
      @user_address = @user.build_user_address
      render :new_user_address, status: :accepted
    end
  end

  def create_user_address
    @user = User.new(session['devise.regist_data']['user'])
    @user_address = UserAddress.new(user_address_params)
    render :new_user_address, status: :unprocessable_entity and return unless @user_address.valid?

    @user.build_user_address(@user_address.attributes)
    @user.save
    session['devise.regist_data']['user'].clear
    sign_in(:user, @user)

    redirect_to root_path
  end

  private

  def user_address_params
    params.require(:user_address).permit(:user_postal_code, :prefecture_id, :user_city,
                                         :user_addresses, :user_building, :user_phone_number)
  end

  def new_user_address
    @user_address = UserAddress.new
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @items = @user.items.page(params[:page]).per(15)

    if user_signed_in?
      Payjp.api_key = ENV['PAYJP_SECRET_KEY']
      @card = Card.find_by(user_id: @user.id)

      if @card.present? && @card.customer_token.present?
        customer = Payjp::Customer.retrieve(@card.customer_token)
        @card_info = customer.cards.first if customer.cards.present?
        # 以降の処理（顧客情報およびカード情報が存在する場合の処理）
      end
    else
      # ログインしていない場合の処理（例: ログインページへのリダイレクト）
      redirect_to new_user_session_path, notice: 'ログインまたはアカウント登録が必要です。続行する前にサインインまたはサインアップしてください。'
    end
  end

  def update
    if current_user.update(user_params) # 更新出来たかを条件分岐する
      redirect_to root_path # 更新できたらrootパスへ
    else
      redirect_to action: 'show' # 失敗すれば再度マイページへ
    end
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email) # 編集出来る情報を制限
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>

<% breadcrumb :users_edit %>

<div class="Account__Page">
  <div class="AccountPage__title">
    <h1>ユーザー情報</h1>
  </div><br>
</div>
<div class="AccountPage__form">
  <%= form_for(current_user) do |f| %>
    <div class="FormField">
      <div class="FormField__name">
        <%= f.label :nickname %>
      </div>
      <div class="FormField__name">
        <%= f.text_field :nickname, autofocus: true %>
      </div>
    </div>
    <div class="FormField">
      <div class="FormField__email">
        <%= f.label :email %>
      </div>
      <div class="FormField__email">
        <%= f.email_field :email %>
      </div>
      <br>
    </div>
    <%= f.submit "更新する" %>
  <% end %>
</div>
<div>
  <%= link_to "マイページへ戻る", user_path(current_user), class: "back_" %>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<% breadcrumb :users_show %>

<div class="AccountPage">
  <div class="AccountPage__title">
    <h1>マイページ</h1>
  </div>
  <br>
  <div class="User_info">
    <div class="Account__info">
      ユーザー情報
    </div>
    <% unless current_user.id == @user.id %>
      <table class="user-detail-table">
        <tbody>
          <tr>
            <th class="user-detail-item">ニックネーム</th>
            <td class="user-detail-value">
              <%= @user.nickname %>
              <% if @user.followed_by?(current_user) %>
                <%=link_to "フォロー中", user_relationships_path(@user.id), class: "btn", data: { turbo_method: :delete } %>
              <% else %>
                <%=link_to "フォローする", user_relationships_path(@user.id), class: "btn", data: { turbo_method: :post } %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
        <h3>フォロー</h3>
        <% @user.followings.each do |user| %>
          <p class=“f-user”><%= link_to user.nickname, user_path(user.id) %></p>
        <% end %>
        <h3>フォロワー</h3>
        <% @user.followers.each do |user| %>
          <p class=“f-user”><%= link_to user.nickname, user_path(user.id) %></p>
        <% end %>
      </div>
    <% end %>
    <% if current_user.id == @user.id %>
      <table class="user-detail-table">
        <tbody>
          <tr>
            <th class="user-detail-item">ニックネーム</th>
            <td class="user-detail-value"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="user-detail-item">メールアドレス</th>
            <td class="user-detail-value"><%= current_user.email %></td>
          </tr>
          <tr>
            <th class="user-detail-item">お名前(全角)</th>
            <td class="user-detail-value"><%= current_user.last_name + ' ' + current_user.first_name %></td>
          </tr>
          <tr>
            <th class="user-detail-item">お名前(カナ)</th>
            <td class="user-detail-value"><%= current_user.last_name_kana + ' ' + current_user.first_name_kana %></td>
          </tr>
          <tr>
            <th class="user-detail-item">生年月日</th>
            <td class="user-detail-value"><%= current_user.birth_date %></td>
          </tr>
          <tr>
            <th class="user-detail-item">住所(まだ保存機能つけていない)</th>
            <td class="user-detail-value"><%= current_user.nickname %></td>
          </tr>
        </tbody>
      </table>
      <div class="edit-btn">
        <%= link_to "ユーザー情報更新", edit_user_path, class: "edit-blue-btn" %>
      </div>
      <div class="Card__title">
        カード情報
      </div>
    <% end %>
  </div>
    <% if current_user.id == @user.id %>
      <div class="Card_info">
        <% if @card_info.present? %>
          <table class="card-detail-table">
            <tbody>
              <tr>
                <th class="card-detail-item">【カード番号】</th>
                <td class="card-detail-value"><%= "**** **** **** " + @card_info[:last4] %></td>
              </tr>
              <tr>
                <th class="card-detail-item">【有効期限】</th>
                <td class="card-detail-value"><%= @card_info[:exp_month] %> / <%= @card_info[:exp_year] %></td>
              </tr>
              <tr>
                <th class="card-detail-item">【ブランド】</th>
                <td class="card-detail-value"><%= @card_info[:brand] %></td>
              </tr>
            </tbody>
          </table>
        <% else %>
          <div class="no-user-detail-table">
              カード情報がありません
          </div>
        <% end %>
        <div class="card-edit-btn">
          <br>
          <% if Card.exists?(user_id: current_user.id) %>
            <%= link_to "カード情報更新", edit_card_path(id: @card.id), data: {turbo: false}, class: "edit-orange-btn" %>
            <%= link_to "カード情報削除", card_path(id: @card.id), data: {turbo_method: :delete}, class:"edit-gray-btn" %>
          <% else %>
            <%= link_to "カード情報更新", new_card_path, data: {turbo: false}, class: "edit-orange-btn" %>
          <% end %>
          <br>
        </div>
      </div>
      <div class='follow-follower'>
        <h3>フォロー</h3>
        <% @user.followings.each do |user| %>
          <p class=“f-user”><%= link_to user.nickname, user_path(user.id) %></p>
        <% end %>
        <h3>フォロワー</h3>
        <% @user.followers.each do |user| %>
          <p class=“f-user”><%= link_to user.nickname, user_path(user.id) %></p>
        <% end %>
      </div>
    <% end %>
  <div class='user-item'>
    <%= @user.nickname %>さんの商品一覧
  </div>
  <ul class='item-lists'>
    <% if @items.present? %>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item) do %>

            <div class='item-img-content'>
              <%= image_tag item.images[0], class: "item-img" if item.images.attached? %>

              <% if PurchaseRecord.exists?(item_id: item.id) %>
                <div class='sold-out'>
                  <span>Sold Out!!</span>
                </div>
              <% end %>  

            </div>
            <div class='item-info'>
              <h3 class='item'>
                <%= item.item_name %>
              </h3>
              <div class='item-price'>
                <span><%= item.item_price %>円<br><%= ShippingFeeStatus.find(item.shipping_fee_status_id).name %></span>
                <% if user_signed_in? %>
                  <div id="like-btn<%= item.id %>">
                    <%= render partial: "likes/like", locals: { item: item } %>
                    <span class='star-count'><%= item.likes.count %></span>
                  </div>
                <% else %>
                  <div id="like-btn<%= item.id %>">
                    <% if item.likes.exists?(item.id) %>
                        <%= image_tag "yellowstar.png", alt: "いいね済み", class:"star-icon" %>
                    <% else %>
                        <%= image_tag "star.png", alt: "いいねする", class:"star-icon" %>
                    <% end %>
                    <span class='star-count'><%= item.likes.count %></span>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    <% else %>
      <li class='list'>
        <%= link_to '#' do %>
          <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              商品を出品してね！
            </h3>
            <div class='item-price'>
              <span>99999999円<br>(税込み)</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="page">
    <%= paginate @items %>
  </div>
</div>