config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'user_addresses', to: 'users/registrations#new_user_address'
    post 'user_addresses', to: 'users/registrations#create_user_address'
  end
  root to: "items#index"
  resources :items do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :purchase_records, only: [:index, :create]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
  resources :cards, only: [:new, :edit, :update, :create, :destroy]
  resources :categories, only: [:new]
  get '/category/:id', to: 'categories#search'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :purchase_record
  has_many_attached :images
  has_many :likes
  has_many :comments
  has_many :categories
  acts_as_taggable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sales_status, class_name: 'SalesStatus'
  belongs_to :shipping_fee_status, class_name: 'ShippingFeeStatus'
  belongs_to :prefecture
  belongs_to :scheduled_delivery, class_name: 'ScheduledDelivery'

  validates :images, presence: true, length: { in: 1..5, message: 'must be at least 1 and no more than 5' }
  validates :item_name, :item_info, :item_price, presence: true

  # validates :item_name, presence: true, length: { minimum: 1, maximum: 40 }
  # validates :item_info, presence: true, length: { minimum: 1, maximum: 1000 }

  DECIMAL_REGEX = /\A\d+(\.\d+)?\s*\z/
  validates :item_price, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 300,
    less_than_or_equal_to: 9_999_999,
    message: lambda do |_object, data|
               if data[:value].blank?
                 'is not a number'
               elsif data[:value].to_i.to_s == data[:value].to_s && data[:value].to_i < 300
                 'must be greater than or equal to 300'
               elsif data[:value].to_i.to_s == data[:value].to_s && data[:value].to_i > 9_999_999
                 'must be less than or equal to 9999999'
               elsif data[:value].to_s.match?(DECIMAL_REGEX)
                 'must be an integer'
               else
                 'is not a number'
               end
             end
  }

  validate :validate_category_presence

  validates :sales_status_id, :shipping_fee_status_id, :prefecture_id, :scheduled_delivery_id,
            numericality: { other_than: 1, message: "can't be blank" }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[base_tags categories comments images_attachments images_blobs likes prefecture purchase_record
       sales_status scheduled_delivery shipping_fee_status tag_taggings taggings tags user]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id child_category_id created_at grandchild_category_id id item_info item_name item_price
       prefecture_id sales_status_id scheduled_delivery_id shipping_fee_status_id updated_at user_id]
  end

  private

  def validate_category_presence
    return if category_id.present? && child_category_id.present? && grandchild_category_id.present?

    errors.add(:base, 'カテゴリーは未選択にできません')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]
  before_action :move_to_sign_in, except: [:index, :show]
  before_action :set_maincategories, only: [:new, :create]

  def index
    @items = Item.all.order('created_at DESC').page(params[:page]).per(15)
  end

  def new
    @item = Item.new
    @maincategories = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    @item.tag_list.add(params[:tag_list], parse: true)
    if @item.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    @maincategories = Category.where(ancestry: nil)
    return if user_signed_in? && current_user.id == @item.user_id && !PurchaseRecord.exists?(item_id: @item.id)

    redirect_to action: :index
  end

  def update
    @maincategories = Category.where(ancestry: nil)

    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    item = Item.find(params[:id])

    return unless user_signed_in? && current_user.id == item.user_id

    item.destroy
    redirect_to root_path
  end

  def search
    # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:item_name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:item_name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:item_name_cont_any] = squished_keywords.split(' ')
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  def tag_search
    tags = ActsAsTaggableOn::Tag.where('name LIKE ?', "%#{params[:q]}%")
    render json: { tags: tags.pluck(:name) }
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:item_name, :item_info,
                                 :sales_status_id, :shipping_fee_status_id,
                                 :prefecture_id, :scheduled_delivery_id,
                                 :item_price, :category_id,
                                 :child_category_id, :grandchild_category_id,
                                 :tag_list, { images: [] }).merge(user_id: current_user.id)
  end

  def move_to_sign_in
    return if user_signed_in?

    redirect_to new_user_session_path, notice: 'ログインまたはアカウント登録が必要です。続行する前にサインインまたはサインアップしてください。'
  end

  def set_maincategories
    @maincategories = Category.where(ancestry: nil)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div id="previews" class="previews"></div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'item[images][]', id:"item-image", data: {index: 0} %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :item_info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <div class="category">
          <div id="select-wrap">
              <%= f.collection_select :category_id, @maincategories, :id, :name, {include_blank: "---"}, {class: "category-id", id: "parent-category"} %>
          </div>
          <!-- 子カテゴリーのIDを設定するための非表示のフォームフィールド -->
          <%= f.hidden_field :child_category_id, {class: "category-id", id: "child-category-id"} %>
          <!-- 孫カテゴリーのIDを設定するための非表示のフォームフィールド -->
          <%= f.hidden_field :grandchild_category_id, {class: "category-id", id: "grandchild-category-id"} %>
        </div>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sales_status_id, SalesStatus.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_status_id, ShippingFeeStatus.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:scheduled_delivery_id, ScheduledDelivery.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :item_price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path(@item), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<% breadcrumb :root %>

<div class='main'>
  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>
    <ul class='item-lists'>
      <% if @items.present? %>
        <% @items.each do |item| %>
          <li class='list'>
            <%= link_to item_path(item), data: {turbo: false} do %>

              <div class='item-img-content'>
                <%= image_tag item.images[0], class: "item-img" if item.images.attached? %>

                <% if PurchaseRecord.exists?(item_id: item.id) %>
                  <div class='sold-out'>
                    <span>Sold Out!!</span>
                  </div>
                <% end %>  

              </div>
              <div class='item-info'>
                <h3 class='item'>
                  <%= item.item_name %>
                </h3>
                <div class='item-price'>
                  <span><%= item.item_price %>円<br><%= ShippingFeeStatus.find(item.shipping_fee_status_id).name %></span>
                  <% if user_signed_in? %>
                    <div id="like-btn<%= item.id %>">
                      <%= render partial: "likes/like", locals: { item: item } %>
                      <span class='star-count'><%= item.likes.count %></span>
                    </div>
                  <% else %>
                    <div id="like-btn<%= item.id %>">
                      <% if item.likes.exists?(item.id) %>
                          <%= image_tag "yellowstar.png", alt: "いいね済み", class:"star-icon" %>
                      <% else %>
                          <%= image_tag "star.png", alt: "いいねする", class:"star-icon" %>
                      <% end %>
                      <span class='star-count'><%= item.likes.count %></span>
                    </div>
                  <% end %>
                </div>
              </div>

            <% end %>
          </li>
        <% end %>
      <% else %>
          <li class='list'>
            <%= link_to '#' do %>
              <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
              <div class='item-info'>
                <h3 class='item-name'>
                  商品を出品してね！
                </h3>
                <div class='item-price'>
                  <span>99999999円<br>(税込み)</span>
                  <div class='star-btn'>
                    <%= image_tag "star.png", class:"star-icon" %>
                    <span class='star-count'>0</span>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
  <div class="page">
    <%= paginate @items %>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class="search-page-container">
  <h3>検索ページ</h3>
  <h3><%= link_to 'トップページへ戻る', root_path %></h3>

  <div class='item-contents' id="detailed-search-result-wrapper">
    <%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>
      <div class="search-field">
        <%= f.label :item_name, '商品名' %>
        <%= f.text_field :item_name, placeholder: '商品名', value: params[:q]&.dig(:item_name) %>
      </div>
      <div class="search-field">
        <%= f.label :category_id_eq, 'カテゴリ' %>
        <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {include_blank: "---"}) %>
      </div>
      <div class="search-field">
        <%= f.label :item_price_gteq, '価格'%>
        <%= f.number_field :item_price_gteq %> 円以上
        <%= f.number_field :item_price_lteq %> 円以下
      </div>
      <%= f.submit '検索' %>
    <% end %>

    <ul class='item-lists' id="detailed-search-result">
      <% @items.each do |item| %>
        <li class='list'>
          <div class="posted-content">
            <%= link_to item_path(item.id) do %>
              <%= image_tag item.images.first, class: "item-img" %>
            <% end %>
            <br>
            <p class="item-name">
              <%= item.item_name %>
            </p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.item_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.images[0] ,class:"item-box-img" if @item.images.attached? %>
      <div class="other-images">
        <% @item.images[1..-1].each do |image| %>
          <div class="other-image">
            <%= image_tag image ,class:"other--image" %>
          </div>
        <%end%>
      </div>      
      <% if PurchaseRecord.exists?(item_id: @item.id) %>
        <div class="sold-out">
          <span>Sold Out!!</span>
        </div>
      <% end %>  
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.item_price %>
      </span>
      <span class="item-postage">
        <%= ShippingFeeStatus.find(@item.shipping_fee_status_id).name %>
      </span>
    </div>

    <% if user_signed_in? && current_user.id == @item.user_id %>
      <% unless PurchaseRecord.exists?(item_id: @item.id) %>
        <%= link_to "商品の編集", edit_item_path(@item), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", "#", data: {turbo_method: :delete}, class:"item-destroy" %>
      <% end %>
    <% end %>

    <% if user_signed_in? && current_user.id != @item.user_id %>
      <% unless PurchaseRecord.exists?(item_id: @item.id) %>
        <%= link_to "購入画面に進む", item_purchase_records_path(item_id: @item.id), data: {turbo: false}, class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.item_info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value">
            <%= link_to User.find(@item.user_id).nickname, user_path(@item.user_id), class: "user--nickname" %>
            <% if User.find(@item.user_id).followed_by?(current_user) %>
              <%=link_to "フォロー中", user_relationships_path(User.find(@item.user_id), item_id: @item.id), class: "btn", data: { turbo_method: :delete } %>
            <% else %>
              <%=link_to "フォローする", user_relationships_path(User.find(@item.user_id), item_id: @item.id), class: "btn", data: { turbo_method: :post } %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value">
            <%= Category.find(@item.category_id).name %><br>
            <%= Category.find(@item.child_category_id).name %><br>
            <%= Category.find(@item.grandchild_category_id).name %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value">
            <% @item.tag_list.each do |tag| %>
              <span class="tag"><%= tag %></span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= SalesStatus.find(@item.sales_status_id).name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= ShippingFeeStatus.find(@item.shipping_fee_status_id).name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= Prefecture.find(@item.prefecture_id).name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= ScheduledDelivery.find(@item.scheduled_delivery_id).name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <% if user_signed_in? %>
          <div id="like-btn<%= @item.id %>">
            <%= render partial: "likes/favo", locals: { item: @item } %>
            <span class='star-count'>お気に入り <%= @item.likes.count %></span>
          </div>
        <% else %>
          <div id="like-btn<%= @item.id %>">
            <% if @item.likes.exists?(@item.id) %>
                <%= image_tag "yellowstar.png", alt: "いいね済み", class:"favorite-star-icon", width:"20",height:"20" %>
            <% else %>
                <%= image_tag "star.png", alt: "いいねする", class:"favorite-star-icon" %>
            <% end %>
            <span class='star-count'>お気に入り <%= @item.likes.count %></span>
          </div>
        <% end %>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>
  <div id="comments" class="comments">
    <h4 class="comment-title">＜コメント一覧＞</h4>
    <% @item.comments.each do |comment| %>
      <div class="comment">
        <p class="user-comment-name"><%= comment.user.nickname %>： </p>
        <p class="user-comment"><%= comment.text%></p>
        <p class="space"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
    <% end %>
  </div>
  <div class="comment-box">
    <% if user_signed_in? && !PurchaseRecord.exists?(item_id: @item.id) %>
      <%= form_with model: [@item, @comment], id: "comment-form" do |f| %>
        <%= f.text_area :text , class: "comment-text"%>
        <p class="comment-warn">
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <button type="submit" class="comment-btn">
          <%= image_submit_tag("comment.png", alt: "コメントをする", class: "comment-flag-icon", width: "20", height: "25") %>
          <span>コメントする<span>
        </button>
      <% end %>
    <% end %>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= Category.find(@item.category_id).name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>