config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'user_addresses', to: 'users/registrations#new_user_address'
    post 'user_addresses', to: 'users/registrations#create_user_address'
  end
  root to: "items#index"
  resources :items do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :purchase_records, only: [:index, :create]
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
  resources :cards, only: [:new, :edit, :update, :create, :destroy]
  resources :categories, only: [:new]
  get '/category/:id', to: 'categories#search'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  attr_accessor :token

  validates :token, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    gon.public_key = ENV['PAYJP_PUBLIC_KEY']
    redirect_to root_path if user_signed_in? && current_user.card
  end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # 環境変数を読み込む
    customer = Payjp::Customer.create(
      description: 'test', # テストカードであることを説明
      card: params[:token] # 登録しようとしているカード情報
    )
    card = Card.new( # 顧客トークンとログインしているユーザーを紐付けるインスタンスを生成
      token: params[:token], # カード情報
      customer_token: customer.id, # 顧客トークン
      user_id: current_user.id # ログインしているユーザー
    )
    if card.save
      redirect_to user_path(current_user)
    else
      redirect_to action: 'new' # カード登録画面へリダイレクト
    end
  end

  def edit
    gon.public_key = ENV['PAYJP_PUBLIC_KEY']
    @card = Card.find(params[:id])
  end

  def update
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']

    @card = Card.find(params[:id])

    # 顧客情報を取得
    customer = Payjp::Customer.retrieve(@card.customer_token)

    # カード情報を新しく追加
    new_card_token = params[:token] # 新しいトークンを取得

    if new_card_token.present?
      # 顧客情報を更新
      customer.card = new_card_token
      customer.save

      # カード情報をデータベースに保存
      if @card.update(
        token: new_card_token,
        customer_token: customer.id,
        user_id: current_user.id # ユーザーIDを追加
      )
        redirect_to user_path(current_user), notice: 'カード情報が更新されました。'
      else
        flash[:alert] = 'カード情報の更新に失敗しました。'
        redirect_to edit_card_path
      end
    else
      flash[:alert] = '新しいカード情報のトークンがありません。'
      redirect_to edit_card_path
    end
  end

  def destroy
    @card = Card.find(params[:id])

    return unless user_signed_in? && current_user.id == @card.user_id

    @card.destroy
    redirect_to user_path(current_user)
  end

  private

  def card_params
    params.require(:card).permit(:token, :customer_token, :other_attribute)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<%= include_gon %>

<%= render "shared/header" %>

<div class="AccountPage">
  <div class="AccountPage__title">
    <h1>カード情報更新</h1>
  </div><br>
</div>
<%= form_with model: current_user.card, url: card_path(current_user.card), data: { turbo: false }, id: 'charge-form', class: 'card-form', local: true do |f| %>
  <div class='form-wrap'>
    <p>カード番号</p>
    <div id="number-form" class="input-default">
      <%= f.text_field :card_number %>
    </div>
  </div>
  <div class='form-wrap'>
    <p>期限</p>
    <div id="expiry-form" class="input-default">
      <%= f.text_field :expiration_date %>
    </div>
  </div>
  <div class='form-wrap'>
    <p>カード背面4桁もしくは3桁の番号</p>
    <div id="cvc-form" class="input-default">
      <%= f.text_field :cvc %>
    </div>
  </div>
  <%= hidden_field_tag '_method', 'patch' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "更新する", class: "button", id: "button" %>
<% end %>
<div>
  <%= link_to "マイページへ戻る", user_path(current_user), class: "back" %>
</div>

app/views/cards/new.html.erb
<%= include_gon %>

<%= render "shared/header" %>

<% breadcrumb :cards_new %>

<div class="Account__Page">
  <div class="AccountPage__title">
    <h1>カード情報登録</h1>
  </div><br>
</div>
<%= form_with  url: cards_path, data: {turbo: false}, id: 'charge-form', class: 'card--form',local: true do |f| %>
  <div class='form--wrap'>
    <p>カード番号</p>
    <div id="number-form" class="input--default"></div>
  </div>
  <div class='form--wrap'>
    <p>期限</p>
    <div id="expiry-form" class="input--default"></div>
  </div>
  <div class='form--wrap'>
    <p>カード背面4桁もしくは3桁の番号</p>
    <div id="cvc-form" class="input--default"></div>
  </div>
  <%= f.submit "登録する", class:"button", id: "button" %>
<% end %>
<div>
  <%= link_to "マイページへ戻る", user_path(current_user), class: "back_" %>
</div>